// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeZFPbQWPsqnnIg8H-vHpYVsjaCopnYD4',
    appId: '1:203577707384:web:e4e7a51a0268258dc5968d',
    messagingSenderId: '203577707384',
    projectId: 'chatapp-34240',
    authDomain: 'chatapp-34240.firebaseapp.com',
    storageBucket: 'chatapp-34240.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqg_o_XO494SCI86QGuilDFKIEU2T5GAQ',
    appId: '1:203577707384:android:c34bde927d68f976c5968d',
    messagingSenderId: '203577707384',
    projectId: 'chatapp-34240',
    storageBucket: 'chatapp-34240.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwyyp7Sk5vI-M8x92sKpyX2fuRBxX1tLo',
    appId: '1:203577707384:ios:62a825a91fcdb93dc5968d',
    messagingSenderId: '203577707384',
    projectId: 'chatapp-34240',
    storageBucket: 'chatapp-34240.firebasestorage.app',
    iosBundleId: 'com.example.chatClient',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwyyp7Sk5vI-M8x92sKpyX2fuRBxX1tLo',
    appId: '1:203577707384:ios:62a825a91fcdb93dc5968d',
    messagingSenderId: '203577707384',
    projectId: 'chatapp-34240',
    storageBucket: 'chatapp-34240.firebasestorage.app',
    iosBundleId: 'com.example.chatClient',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCeZFPbQWPsqnnIg8H-vHpYVsjaCopnYD4',
    appId: '1:203577707384:web:c66fc42028444abac5968d',
    messagingSenderId: '203577707384',
    projectId: 'chatapp-34240',
    authDomain: 'chatapp-34240.firebaseapp.com',
    storageBucket: 'chatapp-34240.firebasestorage.app',
  );
}
